Fix compile error "isatty was not declared"; missing unistd.h include
When I built apitrace on Fedora 16, using the usual:

	cmake -H. -Bbuild
	make -C build

...then I got this compile error:

	apitrace/cli/cli_dump.cpp: In function ‘int command(int, char**)’:
	apitrace/cli/cli_dump.cpp:176:25: error: ‘isatty’ was not declared in this scope